export const warlockSpellTable = [
  { level: 1, knownSpells: 2, slots: 1, slotLevel: 1 },
  { level: 2, knownSpells: 3, slots: 2, slotLevel: 1 },
  { level: 3, knownSpells: 4, slots: 2, slotLevel: 2 },
  { level: 4, knownSpells: 5, slots: 2, slotLevel: 2 },
  { level: 5, knownSpells: 6, slots: 2, slotLevel: 3 },
  { level: 6, knownSpells: 7, slots: 2, slotLevel: 3 },
  { level: 7, knownSpells: 8, slots: 2, slotLevel: 4 },
  { level: 8, knownSpells: 9, slots: 2, slotLevel: 4 },
  { level: 9, knownSpells: 10, slots: 2, slotLevel: 5 },
  { level: 10, knownSpells: 11, slots: 2, slotLevel: 5 },
  { level: 11, knownSpells: 12, slots: 3, slotLevel: 5 },
  { level: 12, knownSpells: 12, slots: 3, slotLevel: 5 },
  { level: 13, knownSpells: 13, slots: 3, slotLevel: 5 },
  { level: 14, knownSpells: 13, slots: 3, slotLevel: 5 },
  { level: 15, knownSpells: 14, slots: 3, slotLevel: 5 },
  { level: 16, knownSpells: 14, slots: 3, slotLevel: 5 },
  { level: 17, knownSpells: 15, slots: 4, slotLevel: 5 },
  { level: 18, knownSpells: 15, slots: 4, slotLevel: 5 },
  { level: 19, knownSpells: 15, slots: 4, slotLevel: 5 },
  { level: 20, knownSpells: 15, slots: 4, slotLevel: 5 },
];
